In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("../data/processed/cleaned_jobs.csv")

print(df.shape)

df.head()

(97682, 18)

,title,jobid,currency,jobuploaded,companyname,tagsandskills,experience,salary,location,companyid,reviewscount,aggregaterating,jobdescription,minimumsalary,maximumsalary,minimumexperience,maximumexperience,avg_experience
0,Sr. HR Recruiter (NON IT),270925008041,INR,6 Days Ago,Orion,"Communication,Manpower,Staffing,Convincing Pow...",2-4 Yrs,2-4 Lacs PA,Kolkata(Chinar Park),645563,965.0,3.7,Preferred candidate profile . .,200000.0,400000.0,2.0,4.0,3.0
1,Fire And Safety Officer,270925007584,INR,6 Days Ago,"Apollo Hospitals International Limited, Ahmedabad","Safety Officer Activities,Fire Protection,Fire...",6-11 Yrs,3-5 Lacs PA,"Gandhinagar, Ahmedabad",14072,5162.0,4.0,"Ensure active Fire Protection System,such as F...",300000.0,500000.0,6.0,11.0,8.5
2,Opening For Performance Marketing - Chennai,270925007492,INR,6 Days Ago,TVS Credit Services Ltd,"Performance Marketing,User Acquisition,growth ...",12-18 Yrs,Not disclosed,Chennai,1324750,2892.0,4.2,MBA Marketing (preferred Tier II or III B- Sch...,0.0,0.0,12.0,18.0,15.0
3,Medical Billing Executive,270925007443,INR,6 Days Ago,GNR Global Services,"Fluent English,Spoken English,Good English Com...",0-3 Yrs,"70,000-2 Lacs PA","Mohali, Chandigarh, Kharar, Zirakpur",123804403,965.0,3.7,Job Title-Medical Billing Executive\nLocation-...,70000.0,200000.0,0.0,3.0,1.5
4,Senior Group Product Manager - CNS Therapy,270925007430,INR,6 Days Ago,Cadila Pharmaceuticals,"Product Marketing,CNS,Product Management,Nephr...",5-10 Yrs,8-18 Lacs PA,Ahmedabad,14957,2134.0,3.4,Principal Tasks & Responsibilities : (Please w...,800000.0,1800000.0,5.0,10.0,7.5

In [3]:
df.columns.tolist()

['title',
 'jobid',
 'currency',
 'jobuploaded',
 'companyname',
 'tagsandskills',
 'experience',
 'salary',
 'location',
 'companyid',
 'reviewscount',
 'aggregaterating',
 'jobdescription',
 'minimumsalary',
 'maximumsalary',
 'minimumexperience',
 'maximumexperience',
 'avg_experience']

In [4]:
df["salary_band"] = pd.cut(
    df["maximumsalary"],
    bins=[0,300000,600000,1000000,2000000,10000000],
    labels=[
        "Low",
        "Medium",
        "High",
        "Very High",
        "Premium"
    ]
)

df["salary_band"].value_counts()

salary_band
Medium       13545
Low           6252
High          5422
Very High     4551
Premium       3356
Name: count, dtype: int64

In [5]:
df["experience_category"] = pd.cut(
    df["avg_experience"],
    bins=[0,2,5,8,50],
    labels=[
        "Entry",
        "Mid",
        "Senior",
        "Expert"
    ]
)

df["experience_category"].value_counts()

experience_category
Mid       35413
Senior    27289
Expert    20365
Entry     14083
Name: count, dtype: int64

In [6]:
df["rating_category"] = pd.cut(
    df["aggregaterating"],
    bins=[0,3,4,5],
    labels=[
        "Average",
        "Good",
        "Excellent"
    ]
)

df["rating_category"].value_counts()

rating_category
Good         82949
Excellent     9654
Average       5079
Name: count, dtype: int64

In [7]:
df["salary_gap"] = (
    df["maximumsalary"] -
    df["minimumsalary"]
)

df[[
    "minimumsalary",
    "maximumsalary",
    "salary_gap"
]].head()

   minimumsalary  maximumsalary  salary_gap
0       200000.0       400000.0    200000.0
1       300000.0       500000.0    200000.0
2            0.0            0.0         0.0
3        70000.0       200000.0    130000.0
4       800000.0      1800000.0   1000000.0

In [8]:
from sklearn.preprocessing import LabelEncoder

le_salary = LabelEncoder()

df["salary_band_encoded"] = le_salary.fit_transform(
    df["salary_band"].astype(str)
)

df.head()

,title,jobid,currency,jobuploaded,companyname,tagsandskills,experience,salary,location,companyid,...,minimumsalary,maximumsalary,minimumexperience,maximumexperience,avg_experience,salary_band,experience_category,rating_category,salary_gap,salary_band_encoded
0,Sr. HR Recruiter (NON IT),270925008041,INR,6 Days Ago,Orion,"Communication,Manpower,Staffing,Convincing Pow...",2-4 Yrs,2-4 Lacs PA,Kolkata(Chinar Park),645563,...,200000.0,400000.0,2.0,4.0,3.0,Medium,Mid,Good,200000.0,2
1,Fire And Safety Officer,270925007584,INR,6 Days Ago,"Apollo Hospitals International Limited, Ahmedabad","Safety Officer Activities,Fire Protection,Fire...",6-11 Yrs,3-5 Lacs PA,"Gandhinagar, Ahmedabad",14072,...,300000.0,500000.0,6.0,11.0,8.5,Medium,Expert,Good,200000.0,2
2,Opening For Performance Marketing - Chennai,270925007492,INR,6 Days Ago,TVS Credit Services Ltd,"Performance Marketing,User Acquisition,growth ...",12-18 Yrs,Not disclosed,Chennai,1324750,...,0.0,0.0,12.0,18.0,15.0,NaN,Expert,Excellent,0.0,5
3,Medical Billing Executive,270925007443,INR,6 Days Ago,GNR Global Services,"Fluent English,Spoken English,Good English Com...",0-3 Yrs,"70,000-2 Lacs PA","Mohali, Chandigarh, Kharar, Zirakpur",123804403,...,70000.0,200000.0,0.0,3.0,1.5,Low,Entry,Good,130000.0,1
4,Senior Group Product Manager - CNS Therapy,270925007430,INR,6 Days Ago,Cadila Pharmaceuticals,"Product Marketing,CNS,Product Management,Nephr...",5-10 Yrs,8-18 Lacs PA,Ahmedabad,14957,...,800000.0,1800000.0,5.0,10.0,7.5,Very High,Senior,Good,1000000.0,4

In [9]:
le_exp = LabelEncoder()

df["experience_encoded"] = le_exp.fit_transform(
    df["experience_category"].astype(str)
)

df.head()

,title,jobid,currency,jobuploaded,companyname,tagsandskills,experience,salary,location,companyid,...,maximumsalary,minimumexperience,maximumexperience,avg_experience,salary_band,experience_category,rating_category,salary_gap,salary_band_encoded,experience_encoded
0,Sr. HR Recruiter (NON IT),270925008041,INR,6 Days Ago,Orion,"Communication,Manpower,Staffing,Convincing Pow...",2-4 Yrs,2-4 Lacs PA,Kolkata(Chinar Park),645563,...,400000.0,2.0,4.0,3.0,Medium,Mid,Good,200000.0,2,2
1,Fire And Safety Officer,270925007584,INR,6 Days Ago,"Apollo Hospitals International Limited, Ahmedabad","Safety Officer Activities,Fire Protection,Fire...",6-11 Yrs,3-5 Lacs PA,"Gandhinagar, Ahmedabad",14072,...,500000.0,6.0,11.0,8.5,Medium,Expert,Good,200000.0,2,1
2,Opening For Performance Marketing - Chennai,270925007492,INR,6 Days Ago,TVS Credit Services Ltd,"Performance Marketing,User Acquisition,growth ...",12-18 Yrs,Not disclosed,Chennai,1324750,...,0.0,12.0,18.0,15.0,NaN,Expert,Excellent,0.0,5,1
3,Medical Billing Executive,270925007443,INR,6 Days Ago,GNR Global Services,"Fluent English,Spoken English,Good English Com...",0-3 Yrs,"70,000-2 Lacs PA","Mohali, Chandigarh, Kharar, Zirakpur",123804403,...,200000.0,0.0,3.0,1.5,Low,Entry,Good,130000.0,1,0
4,Senior Group Product Manager - CNS Therapy,270925007430,INR,6 Days Ago,Cadila Pharmaceuticals,"Product Marketing,CNS,Product Management,Nephr...",5-10 Yrs,8-18 Lacs PA,Ahmedabad,14957,...,1800000.0,5.0,10.0,7.5,Very High,Senior,Good,1000000.0,4,3

In [10]:
le_rating = LabelEncoder()

df["rating_encoded"] = le_rating.fit_transform(
    df["rating_category"].astype(str)
)

df.head()

,title,jobid,currency,jobuploaded,companyname,tagsandskills,experience,salary,location,companyid,...,minimumexperience,maximumexperience,avg_experience,salary_band,experience_category,rating_category,salary_gap,salary_band_encoded,experience_encoded,rating_encoded
0,Sr. HR Recruiter (NON IT),270925008041,INR,6 Days Ago,Orion,"Communication,Manpower,Staffing,Convincing Pow...",2-4 Yrs,2-4 Lacs PA,Kolkata(Chinar Park),645563,...,2.0,4.0,3.0,Medium,Mid,Good,200000.0,2,2,2
1,Fire And Safety Officer,270925007584,INR,6 Days Ago,"Apollo Hospitals International Limited, Ahmedabad","Safety Officer Activities,Fire Protection,Fire...",6-11 Yrs,3-5 Lacs PA,"Gandhinagar, Ahmedabad",14072,...,6.0,11.0,8.5,Medium,Expert,Good,200000.0,2,1,2
2,Opening For Performance Marketing - Chennai,270925007492,INR,6 Days Ago,TVS Credit Services Ltd,"Performance Marketing,User Acquisition,growth ...",12-18 Yrs,Not disclosed,Chennai,1324750,...,12.0,18.0,15.0,NaN,Expert,Excellent,0.0,5,1,1
3,Medical Billing Executive,270925007443,INR,6 Days Ago,GNR Global Services,"Fluent English,Spoken English,Good English Com...",0-3 Yrs,"70,000-2 Lacs PA","Mohali, Chandigarh, Kharar, Zirakpur",123804403,...,0.0,3.0,1.5,Low,Entry,Good,130000.0,1,0,2
4,Senior Group Product Manager - CNS Therapy,270925007430,INR,6 Days Ago,Cadila Pharmaceuticals,"Product Marketing,CNS,Product Management,Nephr...",5-10 Yrs,8-18 Lacs PA,Ahmedabad,14957,...,5.0,10.0,7.5,Very High,Senior,Good,1000000.0,4,3,2

In [11]:
features = [
    "companyname",
    "title",
    "location",
    "minimumsalary",
    "maximumsalary",
    "salary_gap",
    "avg_experience",
    "aggregaterating",
    "reviewscount",
    "salary_band",
    "experience_category",
    "rating_category",
    "salary_band_encoded",
    "experience_encoded",
    "rating_encoded",
    "tagsandskills"
]

feature_df = df[features]

feature_df.head()

,companyname,title,location,minimumsalary,maximumsalary,salary_gap,avg_experience,aggregaterating,reviewscount,salary_band,experience_category,rating_category,salary_band_encoded,experience_encoded,rating_encoded,tagsandskills
0,Orion,Sr. HR Recruiter (NON IT),Kolkata(Chinar Park),200000.0,400000.0,200000.0,3.0,3.7,965.0,Medium,Mid,Good,2,2,2,"Communication,Manpower,Staffing,Convincing Pow..."
1,"Apollo Hospitals International Limited, Ahmedabad",Fire And Safety Officer,"Gandhinagar, Ahmedabad",300000.0,500000.0,200000.0,8.5,4.0,5162.0,Medium,Expert,Good,2,1,2,"Safety Officer Activities,Fire Protection,Fire..."
2,TVS Credit Services Ltd,Opening For Performance Marketing - Chennai,Chennai,0.0,0.0,0.0,15.0,4.2,2892.0,NaN,Expert,Excellent,5,1,1,"Performance Marketing,User Acquisition,growth ..."
3,GNR Global Services,Medical Billing Executive,"Mohali, Chandigarh, Kharar, Zirakpur",70000.0,200000.0,130000.0,1.5,3.7,965.0,Low,Entry,Good,1,0,2,"Fluent English,Spoken English,Good English Com..."
4,Cadila Pharmaceuticals,Senior Group Product Manager - CNS Therapy,Ahmedabad,800000.0,1800000.0,1000000.0,7.5,3.4,2134.0,Very High,Senior,Good,4,3,2,"Product Marketing,CNS,Product Management,Nephr..."

In [12]:
feature_df.isnull().sum()

companyname                0
title                      0
location                   0
minimumsalary              0
maximumsalary              0
salary_gap                 0
avg_experience             0
aggregaterating            0
reviewscount               0
salary_band            64556
experience_category      532
rating_category            0
salary_band_encoded        0
experience_encoded         0
rating_encoded             0
tagsandskills              0
dtype: int64

In [17]:
feature_df["aggregaterating"] = feature_df["aggregaterating"].fillna(0)

feature_df["reviewscount"] = feature_df["reviewscount"].fillna(0)

feature_df["tagsandskills"] = feature_df["tagsandskills"].fillna("Unknown")

feature_df["salary_band"] = feature_df["salary_band"].fillna("Unknown")

feature_df["experience_category"] = feature_df["experience_category"].fillna("Unknown")

feature_df["rating_category"] = feature_df["rating_category"].fillna("Unknown")

In [16]:
feature_df["aggregaterating"] = feature_df["aggregaterating"].fillna(0)
feature_df["reviewscount"] = feature_df["reviewscount"].fillna(0)
feature_df["tagsandskills"] = feature_df["tagsandskills"].fillna("Unknown")

# Add Unknown category before filling
feature_df["salary_band"] = (
    feature_df["salary_band"]
    .cat.add_categories(["Unknown"])
    .fillna("Unknown")
)

feature_df["experience_category"] = (
    feature_df["experience_category"]
    .cat.add_categories(["Unknown"])
    .fillna("Unknown")
)

feature_df["rating_category"] = (
    feature_df["rating_category"]
    .cat.add_categories(["Unknown"])
    .fillna("Unknown")
)

In [18]:
feature_df.to_csv(
    "../data/processed/final_jobs.csv",
    index=False
)

print("Feature Engineering Completed!")

print(feature_df.shape)

Feature Engineering Completed!
(97682, 16)